# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6eac04f842e53ddd1c24623a9ce805056ba1b48a6cb81b6372731224f67eef3a1f5dd0ab0e1beb48d10c6128ee6e4147d2068a42b42ca79af8c45766eb078ea

test:
  secret_key_base: 42ae671ce89e24792e4375f6a9c8abf7ba481f4703a79864ac4bed5fb71bc346397e41e4f3f37b2b4d04a4dc88c43376693d638f1ad378c7cc74475d190b6b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
